version: "2"

networks: 
  consoapp.net:
    driver: bridge

services:
  client:
    image: node
    container_name: consoapp_client
    user: "node"
    working_dir: /app/client
    volumes:
      - ./client:/app/client
    command: "npm run serve"
    ports:
      - "80:8080"
    networks: 
      - 'consoapp.net'
  api:
    image: node
    container_name: consoapp_api
    user: "node"
    working_dir: /app/client
    volumes:
      - ./api:/app/client
    command: "npm run dev"
    ports:
      - "8080:8080"
    networks: 
      - 'consoapp.net'
    links: 
      - database:mongodb
      
  database:
    image: mongo
    restart: always
    container_name: database
    environment:
        - MONGO_INITDB_DATABASE=ConsoApp
        - MONGO_INITDB_USERNAME=root
        - MONGO_INITDB_PASSWORD=example
    volumes:
        - ./mongo-volume:/data/db
    ports:
        - '27017:27017'
    networks: 
        - 'consoapp.net'

  dbmanager:
    image: mongo-express
    networks:
      - consoapp.net
    ports:
      - "8081:8081"
    links:
      - database:mongo