version: "3"

services:
  client:
    build:
      context: ./api
    command: "npm run serve"
    ports:
      - "22000:8080"

  api:
    build:
      context: ./client
    command: "npm run dev"
    ports:
      - "8080:8080"
    links: 
      - database:mongodb
      
  database:
    image: mongo:4.2
    restart: always
    environment:
        - MONGO_INITDB_DATABASE=ConsoApp
        - MONGO_INITDB_USERNAME=root
        - MONGO_INITDB_PASSWORD=example
    volumes:
        - ./mongo-volume:/data/db
    ports:
        - '27017:27017'
